on:
  workflow_dispatch:
    inputs:
      proxy:
        description: "Proxy URL"
        required: true
        default: ""
name: Proxy Tester
jobs:
  get:
    name: Proxy Tester
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: sudo apt update
      - run: sudo apt-get install curl
      - run: curl -x $proxy -L https://api.myip.com > output.json
        env:
          proxy: ${{ github.event.inputs.proxy }}
      - uses: actions/upload-artifact@v3
        with:
          name: output.json
          path: output.json
